{START_FORM}
{CAL_URL}{IMPORTCALENDAR}<br /><br /><br />
{DELETE_CALENDAR_LABEL}{DELETE_CALENDAR_DROPDOWN}<br /><br />
{DELETE_CHECKBOX_LABEL}{DELETE_CALENDAR_CHECKBOX}{DELETE_CALENDAR_BUTTON}
{END_FORM}
