<?php

define('SCHEDULER_ENTRY_YEAR_BUFFER', 5);

define('SCHEDULER_ENTRY_MODE_DAILY', 1);
define('SCHEDULER_ENTRY_MODE_WEEKLY', 2);
define('SCHEDULER_ENTRY_MODE_MONTHLY', 3);
define('SCHEDULER_ENTRY_MODE_YEARLY', 4);
define('SCHEDULER_ENTRY_MODE_EVERY', 5);

define('SCHEDULER_ENTRY_MONTHLY_BEGIN', 1);
define('SCHEDULER_ENTRY_MONTHLY_END', 2);
define('SCHEDULER_ENTRY_MONTHLY_EVERY', 3);
