DROP TABLE mod_book_ban;
DROP TABLE mod_book_com;
DROP TABLE mod_book_config;
DROP TABLE mod_book_data;
DROP TABLE mod_book_ip;
DROP TABLE mod_book_pics;
DROP TABLE mod_book_private;
DROP TABLE mod_book_smilies;
DROP TABLE mod_book_words;