{START_FORM}
<!-- BEGIN MESSAGE -->
{MESSAGE}<br /><br />
<!-- END MESSAGE -->
{COUNTRY_LABEL}:&#160;{JAS_DOCUMENT_COUNTRY}<br /><br />
{COURT_TYPE_LABEL}:&#160;{JAS_DOCUMENT_COURT_TYPE}<br /><br />
{FROM_LABEL}:&#160;{JAS_DOCUMENT_FROM_YEAR}-{JAS_DOCUMENT_FROM_MONTH}-{JAS_DOCUMENT_FROM_DAY}&#160;<b><i>yyyy-mm-dd</i></b><br />
&#160;&#160;&#160;&#160;{TO_LABEL}:&#160;{JAS_DOCUMENT_TO_YEAR}-{JAS_DOCUMENT_TO_MONTH}-{JAS_DOCUMENT_TO_DAY}&#160;<b><i>yyyy-mm-dd</i></b><br /><br />
{KEYWORD_LABEL}:&#160;{JAS_DOCUMENT_KEYWORDS}<br /><br />
{FULL_TEXT_LABEL}:&#160;{JAS_DOCUMENT_FULL_TEXT}<br /><br />
{JAS_SUBMIT}
{END_FORM}
